FROM public.ecr.aws/lambda/python@sha256:a05b85bc8919d6c7db4f438a616bbb1ea8af5804e3f0a9d59acc38b624e9b711

# Install required libraries
RUN dnf install -y postgresql-devel gcc python3-devel

# Install Python dependencies
RUN pip install pandas boto3 requests SQLAlchemy psycopg2 beautifulsoup4 lxml

# Copy your application code
COPY package/ /var/task/

# Ensure the script is executable
RUN chmod 755 /var/task/main.py

# Lambda entry point
CMD [ "main.lambda_handler" ]